### ISSUE TITLE
For TX60, probe temperature is not exposed

### ISSUE THREAD

**Issue by LordJohnWhorfin** [jhschuster/homebridge-lacrosseweb#2]
The TX60 has a built-in humidity and temperature sensor but also a probe. That is the most important value reported and it should be exposed. Currently only ambient temperature and humidity are reported.

**Comment by LordJohnWhorfin** [comment]
I've made a change that seems to work although I couldn't figure out how to give them two different names; they appear as two different temperature readings with the same name. That would be the next fix...
Here's a patch of the changes I made to index.js.
[probeTempPatch.diff.zip](https://github.com/jhschuster/homebridge-lacrosseweb/files/4949075/probeTempPatch.diff.zip)

**Comment by DVST8s64** [comment]
> I've made a change that seems to work although I couldn't figure out how to give them two different names; they appear as two different temperature readings with the same name. That would be the next fix...
> Here's a patch of the changes I made to index.js.
> [probeTempPatch.diff.zip](https://github.com/jhschuster/homebridge-lacrosseweb/files/4949075/probeTempPatch.diff.zip)
> (sorry, I closed this by mistake)

I've used your code and it works great showing the probe temp in Hoobs, but in the Home app on the MacBook or iPhone it shows "No Response" and if I click on the accessory it shows "The accessory is not responding."  Did I miss something or need to do something else?  Thanks for any insight.

**Comment by DVST8s64** [comment]
I'm at a loss here.

This is from Home on MacBook: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/55997547/89367628-86f05000-d6a7-11ea-8624-995cebb665fd.png">

This is from within Hoobs (the probe shows -17 as expected):
<img width="474" alt="image" src="https://user-images.githubusercontent.com/55997547/89367683-a8513c00-d6a7-11ea-8648-34ec04f408cf.png">

**Comment by LordJohnWhorfin** [comment]
I'm not familiar with Hoobs; I tested this with Homebridge and it is working as expected, if the gateway is receiving both temperatures I see no reason for it not to forward it to HomeKit, so it could be a problem with Hoobs. Then again it could very well be that my hack is breaking the spec by having a device report two different temperatures and Homebridge is more lenient with it than Hoobs.
If you just want this to work and don't care about the ambient temperature, I would recommend that you just modify the original code so that it reports the probe temperature instead of the ambient temperature. That's very easy, let me know if you need help with it.

**Comment by crowston** [comment]
Giving the two temperature sensors separate names was straightforward: just change the name when calling Service.TemperatureSensor (e.g., Service.TemperatureSensor(name + " ambient"). 

But I have the same problem that DVST8s64 noted: the ambient temperature shows in the Home app but not the probe temperature, even though I can see both being retrieved in the logs and the code to handle them looks identical. There's some subtlty that I'm not seeing.

**Comment by DVST8s64** [comment]
I can see the temp being presented correctly, but no matter what I'm doing it shows in Home as no response.  I tried just changing the ambient_temp to probe_temp and that got rid of the ambient, but I still get no response.  The output from my terminal shows it sees the temp though; current temp has been changed to the probe, that's what it's a negative value.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/55997547/89483212-84562f00-d769-11ea-9bd3-f6e553392215.png">

**Comment by crowston** [comment]
As an experiment, I commented out all references to the ambient temperature and as expected the device showed up in Home with only one temperature, but one that still said "No response". Reading one of the other plugins, I saw a comment that "negative temperatures aren't supported", which seems unbelievable but the probe temperatures are definitely negative, so maybe that's it. I haven't tried taking an absolute value, but will try it.

**Comment by crowston** [comment]
I changed the update for the probe temperature to Math.max(this.details.services.probeTemp.value,0) and it updates just fine. So, go figure. It's hard to imagine that sub-freezing temperatures aren't supported...

**Comment by crowston** [comment]
And Math.max(this.details.services.probeTemp.value,-1) gets "no response" again. So definitely subzero is a problem.

**Comment by DVST8s64** [comment]
I guess I understand they are thinking of positive numbers for most temperature.  But people using these devices to monitor deep freezers will have negative numbers.

**Comment by crowston** [comment]
Sorry, I edited my comment above rather than adding a new one. I would create a patch, except that I edited the file a lot adding debugging statements that I don't have a clean set of changes. I'll try to redownload and edits to see if I can make a clean patch, but perhaps the comments are enough.

**Comment by crowston** [comment]
Here are a few patches: 

1) Reset the minimum temperature to -100 to handle negative values: 
[0002-Reset-minimum-temperature.patch.txt](https://github.com/jhschuster/homebridge-lacrosseweb/files/5045360/0002-Reset-minimum-temperature.patch.txt)

2) Don't create a sensor for the probe if it's not attached: 
[0001-Probe-temperature-optional.patch.txt](https://github.com/jhschuster/homebridge-lacrosseweb/files/5045361/0001-Probe-temperature-optional.patch.txt)

3) If the data weren't recorded within 30 minutes, report out of range values so it shows up as "not responding" (a bit of a hack; probably there's a more elegant way to do this). 
[0005-Check-data-are-current.patch.txt](https://github.com/jhschuster/homebridge-lacrosseweb/files/5045359/0005-Check-data-are-current.patch.txt)

**Comment by DVST8s64** [comment]
Thank you!! This works!!

<img width="355" alt="image" src="https://user-images.githubusercontent.com/55997547/89713719-9ac9d980-d967-11ea-8fcf-62220d9a95c1.png">

**Comment by jhschuster** [comment]
Thank you for adding the functionality!

I've incorporated all your patches into version 1.0.2, with some whitespace cleanups. I can only test on my local setup. It does not have temperature probes, but it's all still working for me with these changes so adding the new features didn't break anything that had been working for me before.

**Comment by jhschuster** [comment]
And apologies for the delay -- for some reason I haven't been getting notified when folks open issues. Only just now saw this.

**Comment by crowston** [comment]
Regarding my hack for obsolete data (#3 above), I came up with what I think is a better approach: 1) in LacrosseWeb.getStatus, add the timestamp to the details; 2) in LacrosseWebDevice.updateData, check if the timestamp for the device data is too old and if so, set details to null; 3) In the service callbacks set up in addService, return an error if the details are null. It seems to be working, but I couldn't find any documentation of what the callback expected the error to look like. 

I created a patch for these changes, but I may not have gotten the before file correct. 

[obsolete_data.patch.txt](https://github.com/jhschuster/homebridge-lacrosseweb/files/5075752/obsolete_data.patch.txt)

**Comment by jhschuster** [comment]
@crowston I took your advice but implemented it a different way so that there's a new configuration variable, noResponseMinutes, that defaults to 30 that controls when the errors are triggered. If you could give it a test, I'd appreciate it.

**Comment by jhschuster** [comment]
I believe the callback expects the error to simply be a string.

**Comment by crowston** [comment]
I installed the new version and it seems to be working, but over night it got caught in a state where it kept logging "Config refresh in progress, queueing callback". I restarted Homebridge and it's working again. I'll keep an eye on it.
