### ISSUE TITLE
Malformed Configuration

### ISSUE THREAD

**Issue by jbk1988** [jhschuster/homebridge-lacrosseweb#5]
Hi, I keep getting a bunch of data that crashes Homebridge on this plugin, and it concludes with:

[LacrosseWeb] Malformed config, skipping.

Any thoughts? it is the correct username / password.

**Comment by jhschuster** [comment]
I'm seeing this too. I suspect that LaCrosse has changed their web interface such that my scraping of it no longer works. I'll let you know what I find.

**Comment by jhschuster** [comment]
See issue #5 for the details. It's working for me now. Update to 1.0.12.
